# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: 'Speed Of Light'
description: Moving as speed of light.
author:
  name: speed-of-light
  email: speed.of.lightt@gmail.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts', 'node_modules', 'scss',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp',
          '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: pretty
paginate: 10
paginate_path: 'page:num'

# Markdown library
markdown_ext: foo
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  # input: GFM  # use Github flavor markdown

pygments: true
